builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: mac
      windows: win
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}_SHA256SUMS"
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  # If you want to manually examine the release before its live, uncomment this line:
  draft: true
changelog:
  skip: true

nfpms:
  # note that this is an array of nfpm configs
  - # You can change the file name of the package.
    # Default: `{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}`
    file_name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Os }}-{{ .Arch }}"

    # Replacements for GOOS and GOARCH in the package name.
    # Keys should be valid GOOSs or GOARCHs.
    # Values are the respective replacements.
    # Default is empty.
    replacements:
      darwin: mac

    # Template to your app's homepage.
    # Default is empty.
    homepage: https://gsm.hayashi-ke.online/

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: Hannes Hayashi

    # Template to your app's description.
    # Default is empty.
    description: Manage Google Workspace resources using a developer-friendly CLI written in Go.

    # Your app's license.
    # Default is empty.
    license: GPLv3

    # Formats to be generated.
    formats:
      - apk
      - deb
      - rpm
